### ISSUE TITLE
The new visual studio code update break the theme 

### ISSUE THREAD

**Issue by HeroFluxx** [MaxfieldWalker/vscode-color-theme-spirited-away#1]
![image](https://cloud.githubusercontent.com/assets/28282044/25724324/47a55a48-3124-11e7-9b5b-022fb04f20a6.png)

**Comment by maxfie1d** [comment]
Thanks for your feedback!

I am going to deal with the VSCode 1.12 update problem within a few days.

Stay tuned.

**Comment by maxfie1d** [comment]
Updated to adapt the theme to the latest VSCode release 1.12.
Please update the extension from VSCode!
